name: buildAndTest
on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]
  workflow_call:
jobs:
  build_and_test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with: 
          node-version: "16.x"
      - name: Installing project dependencies
        run: npm install
      - name: Run unit tests
        run: npm run test:unit
      - name: Run lint
        run: npm run lint
      - name: Building the project
        run: npm run build
      # - name: Run e2e tests
      #   uses: cypress-io/github-action@v2
      #   with:
      #         build: npm run build
      #         start: npm run serve
      #         wait-on: 'http://localhost:8080'