name: deployment
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  buildAndTest:
    uses: ./.github/workflows/buildAndTest.yaml

  deployment:
    runs-on: self-hosted
    needs: buildAndTest
    steps:
      - name: Restart server
        run: sudo service nginx reload
